global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: fsqr
    metrics_path: /metrics
    static_configs:
      - targets:
          - fsqr:3001

  - job_name: hoppify
    metrics_path: /metrics
    static_configs:
      - targets:
          - hoppify:3000
