-- +goose Up
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id TEXT NOT NULL UNIQUE,
    category_level INTEGER NOT NULL CHECK (category_level BETWEEN 1 AND 6),
    category_name TEXT NOT NULL,
    category_label TEXT NOT NULL,
    description TEXT NOT NULL,

    embedding vector(384) NOT NULL,

    fts tsvector GENERATED ALWAYS AS (
        to_tsvector('pg_catalog.simple', description)
    ) STORED
);

CREATE INDEX IF NOT EXISTS categories_fts_idx
    ON categories USING gin (fts);

CREATE INDEX IF NOT EXISTS categories_embedding_hnsw_idx
    ON categories USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- +goose Down
DROP INDEX IF EXISTS categories_embedding_hnsw_idx;
DROP INDEX IF EXISTS categories_fts_idx;
DROP TABLE IF EXISTS categories;
DROP EXTENSION IF EXISTS vector;
