-- +goose Up
CREATE TABLE IF NOT EXISTS geo_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    overture_release TEXT NOT NULL CHECK (overture_release <> ''),
    overture_area_id TEXT NOT NULL CHECK (overture_area_id <> ''),
    overture_division_id TEXT NOT NULL CHECK (overture_division_id <> ''),

    subtype TEXT NOT NULL CHECK (subtype <> ''),
    class TEXT NOT NULL CHECK (class <> ''),
    country TEXT NOT NULL CHECK (country <> ''),
    region TEXT,

    primary_name TEXT NOT NULL CHECK (primary_name <> ''),
    names_text TEXT NOT NULL CHECK (names_text <> ''),
    names_json JSONB NOT NULL DEFAULT '{}'::jsonb,

    wikidata TEXT,
    population BIGINT CHECK (population IS NULL OR population >= 0),
    parent_overture_division_id TEXT,
    admin_level INTEGER,
    local_type TEXT,

    is_land BOOLEAN NOT NULL,
    is_territorial BOOLEAN,

    west_lon DOUBLE PRECISION NOT NULL CHECK (west_lon BETWEEN -180 AND 180),
    south_lat DOUBLE PRECISION NOT NULL CHECK (south_lat BETWEEN -90 AND 90),
    east_lon DOUBLE PRECISION NOT NULL CHECK (east_lon BETWEEN -180 AND 180),
    north_lat DOUBLE PRECISION NOT NULL CHECK (north_lat BETWEEN -90 AND 90),
    center_lon DOUBLE PRECISION GENERATED ALWAYS AS ((west_lon + east_lon) / 2.0) STORED,
    center_lat DOUBLE PRECISION GENERATED ALWAYS AS ((south_lat + north_lat) / 2.0) STORED,

    overture_sources JSONB NOT NULL DEFAULT '[]'::jsonb,
    loaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    CHECK (west_lon <= east_lon),
    CHECK (south_lat <= north_lat)
);

-- +goose Down
DROP TABLE IF EXISTS geo_features;
